### ISSUE TITLE
if you have multiple layers, and then query an edge without specifying the layer, it returns none

### ISSUE THREAD

**Issue by Haaroon** [Pometry/Raphtory#1036]
g.edge should search all layers by default 

g = Graph ()
g.add_edge(1,1,2,{"tx_sent":10},layer="btc")
g.add_edge(1,1,2,{"tx_sent":20},layer="eth")
g.add_edge(1,1,2,{"tx_sent":70},layer="tether")

e = g.layer(["eth","btc"]).edge(1,2) # this returns 1 edge view

e.property("tx_sent").temporal().sum() == 30

e_list = g.layer("btc,eth").edges() 
len(e_list) == 1

e = g.edge(1,2)
e_btc = e.layer("btc")
e_eth = e.layer("eth")
e_btc.property("tx_sent").temporal().sum() < e_eth.property("tx_sent").temporal().sum()

e_eth = e_eth.layer(["eth","btc"])
e_eth.property("tx_sent").temporal().sum() == 30

e = g.edge(1,2)
e.property("tx_sent").temporal().sum() == 100

**Comment by ricopinazo** [comment]
What happens if the same edge is on two different layers? We return a List of edges? That would force us to define the return type to be an Iterator or a Vector in rust, is that alright? In Python we might return either an Edge or a list of edges depending on the case, but that might be confusing as well.

For that reason, by default the function points to the default layer. That allows us to set the return type to Edge and if a user doesn't even know about layers, their code is going to work as expected. That's was my reasoning for these semantics, but maybe we can find a better solution for this.

**Comment by ljeub-pometry** [comment]
A possible solution is to have the `EdgeView` store a vector of `EdgeRef`s. This would also be useful for supporting undirected views.
