### ISSUE TITLE
Add details on supported Python and Rust versions

### ISSUE THREAD

**Issue by abhishektiwari** [Pometry/Raphtory#1332]
Provide details on supported Python and Rust versions in documentation and `README`. Trying to run Python examples with `3.11` and they don't work out of the box.

For [JOSS Review](https://github.com/openjournals/joss-reviews/issues/5940)

**Comment by miratepuffin** [comment]
Hi @abhishektiwari - the examples in the documentation (https://www.raphtory.com/user-guide/installation/) are all working. 

Are you discussing the [examples](https://github.com/Pometry/Raphtory/tree/master/examples) within the repo? Some of these are indeed a little old and need to be cleaned up.  Or are you reffering to the code snippets within the paper? Our API has changed slightly since submission.

**Comment by abhishektiwari** [comment]
Understood. This ticket is for adding supported Python/Rust versions on repository.
